### ISSUE TITLE
Support for relative links

### ISSUE THREAD

**Issue by jurgenhaas** [FeatureBrowser/FeatureBrowser#12]
Just wondering if this could be supporting relative links. So instead of coding the links in Twig like `href="http://{{ baseUrl }}/{{ baseDirectory }}directories/{{ filename }}"` it would be great if the link could be relative like `href="../directories/ {{ filename }}"` but the challenge is that calculating the relative path might be tricky. I'm not experienced enough in Twig yet to determine if that's possible and how.

Use case: if we had those relative links, we could also browser the documentation from the local file system without necessarily knowing the root path of it as this might be different on each developer laptop. And with relative links, it would still work in web browsers like it does today.

I'd be happy to work on this if the module owner gave me some hints.

**Comment by jmauerhan** [comment]
Hi @jurgenhaas - Have you tried leaving baseUrl as an empty string? I believe that would allow you to open the index in the directory and have the same effect.

**Comment by jurgenhaas** [comment]
@jmauerhan that doesn't work, unfortunately. In the Twig templates, some of the links are coded like the one sample above which would result in `http:///docs/directories/something.html` if the baseUrl were empty, i.e. 3 leading slashes and a http schema which would work with the local file system.

In other cases, e.g. if you are in the document `/docs/tags/tag1.html` and you need to link to `/docs/features/feature1/file3.html` then an empty baseUrl without the leading schema would work either, it then really needs to be relative with traversing the path up to the root and then down to the location of the destination again.

**Comment by jmauerhan** [comment]
Okay, I see. If you'd like to do a PR, I'd suggest ensuring baseUrl can be omitted in `src/FeatureBrowser/Cli/GenerateCommand.php`, then editing the views `src/FeatureBrowser/Resources/views` to handle baseUrl only if it's set. 

I haven't seen a ton of interest in the project, so unfortunately there's not any tests or a build process, but you're welcome to contribute. :) I'll see if I can find some time to come back and work on this with a better process.

**Comment by jurgenhaas** [comment]
That was easier than I thought, it's a nice and clean solution purely implemented on the theme layer. When ever a link target should be created, a macro is called and the first parameter is the `tobase` string which is the relative path from the calling instance to the base of the directory. That way, the macro can easily create the link which will always be valid.

That means that (a) the baseUrl is not used anywhere, this will (b) break nothing and continues to work everywhere and (c) the web server setup, should one be used, only needs to point to the main index.html file and everything else is "just"working.

Hope you like that approach?
